### ISSUE TITLE
ImportError for `nucleus.io.gfile`

### ISSUE THREAD

**Issue by youngchanpark** [google/nucleus#31]
Hi, 
I encountered an import error when trying to import `nucleus.io.gfile`. It seems someone reported this problem on a closed issue in Nov 2019 (https://github.com/google/nucleus/issues/14#issuecomment-559605815). 

I'm using macOS 10.14.6, and I've attached the problem below.

```bash
## Start a python3.6 virtualenv to show reproduction of import error
$ python3 -m virtualenv nucleus-import
created virtual environment CPython3.6.11.final.0-64 in 1120ms
  creator CPython3Posix(dest=/Users/YoungChanPark/nucleus-import, clear=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/YoungChanPark/Library/Application Support/virtualenv)
    added seed packages: pip==20.2.2, setuptools==49.6.0, wheel==0.35.1
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

## Activate virtualenv
$ source nucleus-import/bin/activate

## Install Nucleus with Pip
(nucleus-import) $ pip install google-nucleus
Collecting google-nucleus
  Using cached google_nucleus-0.5.3.tar.gz (6.8 MB)
Collecting contextlib2
  Using cached contextlib2-0.6.0.post1-py2.py3-none-any.whl (9.8 kB)
Processing ./Library/Caches/pip/wheels/fc/e6/3f/1616b381f981006664dd5123f06b231bbbb2e7d604a417e2fd/intervaltree-3.1.0-py2.py3-none-any.whl
Collecting absl-py
  Using cached absl_py-0.10.0-py3-none-any.whl (127 kB)
Collecting mock
  Using cached mock-4.0.2-py3-none-any.whl (28 kB)
Collecting numpy
  Using cached numpy-1.19.2-cp36-cp36m-macosx_10_9_x86_64.whl (15.3 MB)
Collecting six
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting protobuf
  Using cached protobuf-3.13.0-cp36-cp36m-macosx_10_9_x86_64.whl (1.3 MB)
Collecting Pillow
  Using cached Pillow-7.2.0-cp36-cp36m-macosx_10_10_x86_64.whl (2.2 MB)
Collecting ipython
  Using cached ipython-7.16.1-py3-none-any.whl (785 kB)
Collecting sortedcontainers<3.0,>=2.0
  Using cached sortedcontainers-2.2.2-py2.py3-none-any.whl (29 kB)
Requirement already satisfied: setuptools in ./nucleus-import/lib/python3.6/site-packages (from protobuf->google-nucleus) (49.6.0)
Collecting pexpect; sys_platform != "win32"
  Using cached pexpect-4.8.0-py2.py3-none-any.whl (59 kB)
Collecting decorator
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting jedi>=0.10
  Using cached jedi-0.17.2-py2.py3-none-any.whl (1.4 MB)
Collecting traitlets>=4.2
  Using cached traitlets-4.3.3-py2.py3-none-any.whl (75 kB)
Collecting prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0
  Using cached prompt_toolkit-3.0.7-py3-none-any.whl (355 kB)
Collecting pygments
  Using cached Pygments-2.7.1-py3-none-any.whl (944 kB)
Collecting pickleshare
  Using cached pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
Collecting backcall
  Using cached backcall-0.2.0-py2.py3-none-any.whl (11 kB)
Collecting appnope; sys_platform == "darwin"
  Using cached appnope-0.1.0-py2.py3-none-any.whl (4.0 kB)
Collecting ptyprocess>=0.5
  Using cached ptyprocess-0.6.0-py2.py3-none-any.whl (39 kB)
Collecting parso<0.8.0,>=0.7.0
  Using cached parso-0.7.1-py2.py3-none-any.whl (109 kB)
Collecting ipython-genutils
  Using cached ipython_genutils-0.2.0-py2.py3-none-any.whl (26 kB)
Collecting wcwidth
  Using cached wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Building wheels for collected packages: google-nucleus
  Building wheel for google-nucleus (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/YoungChanPark/nucleus-import/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/4m/q2rj8ww90ms0jwg7zv4ldwqh0000gn/T/pip-install-0hj3airk/google-nucleus/setup.py'"'"'; __file__='"'"'/private/var/folders/4m/q2rj8ww90ms0jwg7zv4ldwqh0000gn/T/pip-install-0hj3airk/google-nucleus/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/4m/q2rj8ww90ms0jwg7zv4ldwqh0000gn/T/pip-wheel-7e5y8qnk
       cwd: /private/var/folders/4m/q2rj8ww90ms0jwg7zv4ldwqh0000gn/T/pip-install-0hj3airk/google-nucleus/
  Complete output (1 lines):
  This package does not support wheel creation.
  ----------------------------------------
  ERROR: Failed building wheel for google-nucleus
  Running setup.py clean for google-nucleus
Failed to build google-nucleus
DEPRECATION: Could not build wheels for google-nucleus which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Installing collected packages: contextlib2, sortedcontainers, intervaltree, six, absl-py, mock, numpy, protobuf, Pillow, ptyprocess, pexpect, decorator, parso, jedi, ipython-genutils, traitlets, wcwidth, prompt-toolkit, pygments, pickleshare, backcall, appnope, ipython, google-nucleus
    Running setup.py install for google-nucleus ... done
Successfully installed Pillow-7.2.0 absl-py-0.10.0 appnope-0.1.0 backcall-0.2.0 contextlib2-0.6.0.post1 decorator-4.4.2 google-nucleus-0.5.3 intervaltree-3.1.0 ipython-7.16.1 ipython-genutils-0.2.0 jedi-0.17.2 mock-4.0.2 numpy-1.19.2 parso-0.7.1 pexpect-4.8.0 pickleshare-0.7.5 prompt-toolkit-3.0.7 protobuf-3.13.0 ptyprocess-0.6.0 pygments-2.7.1 six-1.15.0 sortedcontainers-2.2.2 traitlets-4.3.3 wcwidth-0.2.5
WARNING: You are using pip version 20.2.2; however, version 20.2.3 is available.
You should consider upgrading via the '/Users/YoungChanPark/nucleus-import/bin/python -m pip install --upgrade pip' command.

# Start Python interpreter
(nucleus-import) $ python3
```

I get an import error when trying to import gfile.
```python3

>>> from nucleus.io import gfile
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/YoungChanPark/nucleus-import/lib/python3.6/site-packages/nucleus/io/gfile.py", line 22, in <module>
    from nucleus.io.python import gfile
ImportError: dlopen(/Users/YoungChanPark/nucleus-import/lib/python3.6/site-packages/nucleus/io/python/gfile.so, 2): no suitable image found.  Did find:
	/Users/YoungChanPark/nucleus-import/lib/python3.6/site-packages/nucleus/io/python/gfile.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Users/YoungChanPark/nucleus-import/lib/python3.6/site-packages/google/protobuf/pyext/_message.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00

>>> from nucleus.io.python import gfile
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/YoungChanPark/nucleus-import/lib/python3.6/site-packages/nucleus/io/python/gfile.so, 2): no suitable image found.  Did find:
	/Users/YoungChanPark/nucleus-import/lib/python3.6/site-packages/nucleus/io/python/gfile.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Users/YoungChanPark/nucleus-import/lib/python3.6/site-packages/google/protobuf/pyext/_message.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
```

**Comment by tedyun** [comment]
Hi Young-Chan,

Thank you for filing this issue. Unfortunately Nucleus does not currently support MacOS as described in the [installation instruction](https://github.com/google/nucleus#installation). If you have any modern linux system available for you, please try the same command in it and let us know if you run into any issue.

Best,
Ted

**Comment by tedyun** [comment]
Closing this ticket - please let us know if you run into any issues in a supported linux system.
