### ISSUE TITLE
ImportError: libbz2.so.1.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by lorrainelim** [google/nucleus#40]
I tried to run the example Nucleus program:

from nucleus.io import vcf

```
with vcf.VcfReader('./clinvar.vcf.gz') as reader:
  print('Sample names in VCF: ', ' '.join(reader.header.sample_names))
  with vcf.VcfWriter('/tmp/filtered.tfrecord', header=reader.header) as writer:
    for variant in reader:
      if variant.quality > 3.01:
        writer.write(variant)
```

but I keep getting this error:
`ImportError: libbz2.so.1.0: cannot open shared object file: No such file or directory`

I have tried two solutions I found online but they did not work: eg
Solution1:
```
sudo yum install libbz2
sudo yum install bzip2-libs
```

Solution 2:
```
sudo ln -s 
sudo ldconfig
```

Seeking your help, thank you very much!

**Comment by lorrainelim** [comment]
Apologies, I should have provided the full error message:

`Traceback (most recent call last):
  File "./analysis.py", line 11, in <module>
    from nucleus.io import vcf
  File "/root/.local/lib/python3.6/site-packages/nucleus/io/vcf.py", line 64, in <module>
    from nucleus.io import genomics_reader
  File "/root/.local/lib/python3.6/site-packages/nucleus/io/genomics_reader.py", line 68, in <module>
    from nucleus.io.python import tfrecord_reader
ImportError: libbz2.so.1.0: cannot open shared object file: No such file or directory
[centos@variant-prioritization-pipeline clinvar]$ python3 ./analysis.py 
Traceback (most recent call last):
  File "./analysis.py", line 3, in <module>
    from nucleus.io import vcf
  File "/home/centos/.local/lib/python3.6/site-packages/nucleus/io/vcf.py", line 64, in <module>
    from nucleus.io import genomics_reader
  File "/home/centos/.local/lib/python3.6/site-packages/nucleus/io/genomics_reader.py", line 68, in <module>
    from nucleus.io.python import tfrecord_reader
ImportError: libbz2.so.1.0: cannot open shared object file: No such file or directory`

**Comment by MariaNattestad** [comment]
Hi @lorrainelim 
What is the environment you are running this from?

**Comment by kishwarshafin** [comment]
hi @lorrainelim ,

I am closing this issue due to having no activity. Please feel free to reopen if you are still facing the issue.
